"""CLI 命令：init — 交互式初始化配置。"""

import getpass
from pathlib import Path

import yaml
from rich.console import Console


def do_init():
    """交互式初始化：3步对话 → 选择 Provider → 输入 API Key → 写入配置。"""
    import datetime

    console = Console()
    config_dir = Path.home() / ".audison"
    env_path = config_dir / ".env"
    config_path = config_dir / "config.yaml"

    # ── 检测已有配置 ──
    if env_path.exists():
        console.print()
        console.print(f"[yellow]⚠ Existing configuration found at {env_path}[/yellow]")
        overwrite = input("  Overwrite? [y/N]: ").strip().lower()
        if overwrite not in ("y", "yes"):
            console.print("  [dim]Keeping existing configuration.[/dim]")
            return

    # ── 横幅 ──
    console.print()
    console.print("  ╔══════════════════════════════════════════════╗")
    console.print("  ║        Audison — Setup             ║")
    console.print("  ╚══════════════════════════════════════════════╝")
    console.print()

    # ── Step 1: 选择 Provider ──
    providers = [
        ("openai",    "OpenAI",         "GPT-4o, GPT-4o-mini"),
        ("anthropic", "Anthropic",      "Claude Sonnet, Claude Haiku"),
        ("ollama",    "Ollama (Local)", "llama3, codellama — no API key needed"),
        ("custom",    "Custom",         "any OpenAI-compatible endpoint"),
    ]

    console.print("[bold]  Choose your AI provider:[/bold]")
    for i, (pid, name, desc) in enumerate(providers, 1):
        console.print(f"  [cyan][{i}][/cyan] {name:<18} [dim]({desc})[/dim]")
    console.print()

    while True:
        choice = input("  Enter number (1-4): ").strip()
        try:
            choice = int(choice)
            if 1 <= choice <= 4:
                break
        except ValueError:
            pass
        console.print("  [red]Please enter a number between 1 and 4.[/red]")

    pid, pname, pdesc = providers[choice - 1]
    console.print()
    console.print(f"  [green]Selected: {pname}[/green]")
    console.print()

    # ── Step 2: API Key（Ollama 跳过）──
    api_key = ""
    if pid != "ollama":
        api_key = getpass.getpass(f"  Enter your {pname} API Key (input hidden): ").strip()
        if not api_key:
            console.print("  [red]API Key cannot be empty. Setup aborted.[/red]")
            return

    # ── Step 3: Custom 额外配置 ──
    endpoint_url = ""
    custom_model = ""
    if pid == "custom":
        endpoint_url = input("  Endpoint URL (e.g. https://api.openai.com/v1): ").strip()
        if not endpoint_url:
            console.print("  [red]Endpoint URL cannot be empty. Setup aborted.[/red]")
            return
        custom_model = input("  Model name (e.g. gpt-4o): ").strip()
        if not custom_model:
            console.print("  [red]Model name cannot be empty. Setup aborted.[/red]")
            return
    console.print()

    # ── 默认模型 ──
    default_models = {
        "openai": "gpt-4o",
        "anthropic": "claude-sonnet-4-20250514",
        "ollama": "llama3",
        "custom": custom_model,
    }

    default_model = default_models[pid]
    if pid != "custom":
        model_input = input(f"  Default model [{default_model}]: ").strip()
        if model_input:
            default_model = model_input
    console.print()

    # ── 写入 ~/.audison/.env ──
    config_dir.mkdir(parents=True, exist_ok=True)

    today = datetime.date.today().isoformat()
    env_lines = [
        "# Audison Configuration",
        f"# Generated by audison init on {today}",
        "",
    ]

    if pid == "ollama":
        env_lines.append("# No API key needed for Ollama (local)")
        env_lines.append("AIFLOW_PROVIDER=ollama")
    elif pid == "custom":
        env_lines.append(f"OPENAI_API_KEY={api_key}")
        env_lines.append(f"CUSTOM_ENDPOINT={endpoint_url}")
    else:
        env_var_map = {
            "openai": "OPENAI_API_KEY",
            "anthropic": "ANTHROPIC_API_KEY",
        }
        env_lines.append(f"{env_var_map[pid]}={api_key}")

    env_lines.append(f"AIFLOW_DEFAULT_MODEL={default_model}")
    env_lines.append("")

    env_path.write_text("\n".join(env_lines) + "\n", encoding="utf-8")

    # ── 写入 ~/.audison/config.yaml ──
    config_data = {
        "default_provider": pid,
        "default_model": default_model,
    }
    if pid == "custom":
        config_data["custom_endpoint"] = endpoint_url

    try:
        with open(config_path, "w", encoding="utf-8") as f:
            yaml.dump(config_data, f, default_flow_style=False, allow_unicode=True)
    except Exception:
        pass

    # ── 完成 ──
    console.print("  " + "─" * 48)
    console.print(f"  [green bold]✅ Configuration saved![/green bold]")
    console.print()
    console.print("  [bold]Next steps:[/bold]")
    console.print("    audison health")
    console.print('    audison audit example -r "Test audit"')
    console.print()
